# frozen_string_literal: true

source "https://rubygems.org"

group :development do
  gem 'rubocop', require: false
  gem 'solargraph', '0.45.0'
end

group :development, :test do
  gem 'pry-byebug'
end
